### ISSUE TITLE
How to deal *fact.txt ?

### ISSUE THREAD

**Issue by luolo-cry** [jun-zeng/ShadeWatcher#10]
hello, I want to konw how to get the *2id.txt parsed from darpa data? i run the  'parsedar ' to parse darpa dataset but only get some *fact.txt. hope for your reply

**Comment by luolo-cry** [comment]
I parsed the "nano_scp" dataset into *fact.txt, and i read paper carefully but still failed to generate *2id.txt, can you give me more detail about extract interaction?

**Comment by PanzerknackerR** [comment]
I am also stuck at the moment. I have used a Darpa data set and converted it into the corresponding *.fact.txt. Thereby I also have the question if what exactly belongs to the bipartite graph. I could not exactly distinguish that in the code. 

And which data sets were used for the TRACE evaluation? Were the attack scenarios in the paper used or the entire TRACE records? 

Many greetings and: Great paper!  I find the concepts combined remarkably well!

**Comment by jctemp** [comment]
I had the same problem that the parser output yield the `*fact.txt` files. I did some research and noticed that the repository was forked by `syssec-utd`. The fork has a feature branch including a [python file](https://github.com/syssec-utd/ShadeWatcher/blob/data-processing-scripts/syssec-data-processing/encoding-parser.py), doing the conversion.

**Comment by jun-zeng** [comment]
To obtain the *2id.txt (e.g., train2id.txt), you need to encode the KG using one-hot encodings by yourself.
