### ISSUE TITLE
 Inquiry regarding the sourcing of pid and ppid in the Triplet::SyscallClone() function in Beat Parser

### ISSUE THREAD

**Issue by wlmnzf** [jun-zeng/ShadeWatcher#11]
Dear Author,

I hope this message finds you well. I am reaching out to inquire about the rationale behind obtaining the pid and ppid values in the Triplet::SyscallClone() function from the "exit" and "pid" fields in the log, respectively, rather than directly using the pid and ppid values provided in the log itself.

In the code snippet you provided:
```
std::string pid = Jval2str(event["auditd"]["data"]["exit"]);
std::string ppid = Jval2str(event["process"]["pid"]);
```
It is observed that the pid and ppid values are sourced from the "exit" and "pid" fields of the log, rather than the pid and ppid values directly available in the log, as shown below:
```
"name": "run-parts",
"exe": "/bin/run-parts",
"pid": "18112",
"ppid": "18109"
```
I would appreciate it if you could kindly provide some insights into the reasons behind this design choice. Understanding the motivation behind this approach would help in comprehending the code's functionality and its relationship with the log data.

Thank you very much for your time and attention. I look forward to your response.

Warm regards,
Limin Wang

**Comment by jctemp** [comment]
To my understanding, the `clone` syscall is similar to `fork`, meaning `clone` creates a new child process based on the current process. The return value of `clone` is probably in `event["auditd"]["data"]["exit"]`, which is the "PID" of the new child. Hence, the PPID is the current process.
Of course, I assume the audit log corresponds to the described behaviour.

Best regards,
Jamie Temple

**Comment by jctemp** [comment]
Here is an example (`/data/examples/nano_scp_1/auditbeat`). We have the process `18109`. It calls clone and has the exit value `18112` which is the PID of `run-parts`.
```json
[
    {
        "@timestamp": "2020-10-31T14:14:47.781Z",
        "process": {
            "name": "sh",
            "exe": "/bin/dash",
            "cwd": "/",
            "args": [
                "sh",
                "-c",
                "/usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin run-parts --lsbsysinit /etc/update-motd.d \u003e /run/motd.dynamic.new"
            ],
            "pid": "18109",
            "ppid": "18104"
        }
    },
    {
        "@timestamp": "2020-10-31T14:14:47.781Z",
        "process": {
            "pid": "18109",
            "ppid": "18104",
            "name": "sh",
            "exe": "/bin/dash"
        },
        "auditd": {
            "data": {
                "syscall": "clone",
                "exit": "18112"
            }
        }
    },
    {
        "@timestamp": "2020-10-31T14:14:47.785Z",
        "process": {
            "name": "run-parts",
            "exe": "/bin/run-parts",
            "pid": "18112",
            "ppid": "18109"
        },
        "auditd": {
            "data": {
                "syscall": "clone",
                "exit": "18113"
            }
        }
    }
]
```

**Comment by wlmnzf** [comment]
> To my understanding, the `clone` syscall is similar to `fork`, meaning `clone` creates a new child process based on the current process. The return value of `clone` is probably in `event["auditd"]["data"]["exit"]`, which is the "PID" of the new child. Hence, the PPID is the current process. Of course, I assume the audit log corresponds to the described behaviour.
> 
> Best regards, Jamie Temple

Thank you very much for your prompt response and the insightful explanation regarding the sourcing of `pid` and `ppid` values in the `Triplet::SyscallClone()` function. I appreciate your time and effort in providing clarity on this matter.

After considering your explanation, it makes perfect sense to source the `pid` from the `"exit"` field and the `ppid` from the `"pid"` field in the log. By utilizing these specific fields, the code can accurately retrieve the relevant process IDs associated with the event, ensuring the correct processing and handling of the log data.

I am grateful for your assistance in helping me understand the rationale behind this design choice. Your response has provided valuable insights and enhanced my comprehension of the code's functionality.

Once again, thank you for your expertise and support. I truly appreciate your time and attention to this matter.

Warm regards！

**Comment by jun-zeng** [comment]
@jctemp Thank you for the answer.
@wlmnzf  I will close this issue then.
