### ISSUE TITLE
Issue: Configure error for libpqxx (c++ postgresql)

### ISSUE THREAD

**Issue by ceporras2** [jun-zeng/ShadeWatcher#16]
I ran into an issue when going through the parser setup. I ran the command 'sudo ./configure --disable-documentation --prefix=$LIB_INSTALL_PATH'.
I got the following error: 'configure: error: This libpqxx version needs at least C++17.'
Are there any recommendations to fix this issue? I went through the optional second step for g++, so I am not sure why I am running into this issue now when steps 1 through 3 went fine.

**Comment by LouisLiuNova** [comment]
I encountered the same issue, but I resolved it by revising the following command. You may need to specify the specific branch to avoid using an unstable or too new version:
```
apt install libpq-dev
git clone https://github.com/jtv/libpqxx.git
cd libpqxx
git checkout 7.0.7 # Verified version
./configure CXXFLAGS="-std=c++17 -O3" --disable-documentation --prefix=$LIB_INSTALL_PATH
make -j8
make install
```

Additionally, you need to check the major version of g++. Version g++-8 is acceptable.

**Comment by ceporras2** [comment]
Including the CXXFLAGS argument in the configuration, as shown above, solved the issues I was having. Thank you! @iridium-soda.
