### ISSUE TITLE
Hello, can you publish the labeled dataset?

### ISSUE THREAD

**Issue by wang1028-yu** [jun-zeng/ShadeWatcher#3]
I'm reading your paper and I found that you claim to manually label the ground truth of of interactions through  their  relations  to  attacks. I would like to ask, can you publish the labeled dataset?

**Comment by jun-zeng** [comment]
Please find our labeled motivating example and the corresponding raw recommendation results in
[gtcache.txt](https://github.com/jun-zeng/ShadeWatcher/files/9851187/gtcache.txt).

**Comment by jun-zeng** [comment]
More details on the results:
TP/TN/FP/FN, #Interactoin, Interactive system entity, label(1:malicious; 0:benign), recommendation results

For exampe,
(T 5 file{name: /proc/12/stat} 0.0 1.3217545) denotes a true nagetive (T).
(T 0 socket{name: 128.55.12.73:548} 1.0 -0.6134615) denotes a true positive (T).

**Comment by wang1028-yu** [comment]
Nice. Thanks
