### ISSUE TITLE
Format of the result

### ISSUE THREAD

**Issue by wang1028-yu** [jun-zeng/ShadeWatcher#4]
Hello, After running the parsing code, I get the output results and save them to ‘../data/encoding/e3_trace’, but I found that the format of the output result is different from the recommend example data which stores at ‘../data/encoding/test’. Do I need to process them into the required format by myself？Or did I miss something.

**Comment by wang1028-yu** [comment]
<img width="336" alt="截屏2022-10-26 09 01 51" src="https://user-images.githubusercontent.com/67589441/197910207-20146049-c246-411c-97ae-ff830334c28a.png">

**Comment by wang1028-yu** [comment]
<img width="282" alt="截屏2022-10-26 09 02 31" src="https://user-images.githubusercontent.com/67589441/197910369-5b6d2cca-09a4-4ea8-a727-57c2e842a18e.png">

**Comment by wang1028-yu** [comment]
especially the file called inter2id_0.txt, I would like to know how to generate a file in this format.

**Comment by jun-zeng** [comment]
Hi, you need to extract system entity interactions from our provenance graph and encode them into the training format. The details of how we perform the interaction extraction can be found in our paper.

**Comment by wang1028-yu** [comment]
Thank you for the explanation.

**Comment by luolo-cry** [comment]
> 谢谢你的解释。

hello, do you konw how to get the *2id.txt? i run the parsedar to parse darpa dataset but only get some *fact.txt. hope for your reply
