### ISSUE TITLE
the predict result of train2id.txt

### ISSUE THREAD

**Issue by wang1028-yu** [jun-zeng/ShadeWatcher#6]
Hello, after running the test data in "data/encoding/test", I try to use this model to predict the data in train2id.txt, so I use the "pred_inter" function in model_eval.py. I constructed the inter_list and pass them into this function and the threshold is 1.5, According to my understanding，I think the data in triain2id.txt are benign. but I got the result that the num of result less than threshold is 3701 while the total num is 5945.
<img width="841" alt="截屏2022-11-30 22 53 17" src="https://user-images.githubusercontent.com/67589441/204829056-c968dfd8-7015-413d-8ca1-d0f1dd3efb43.png">
<img width="224" alt="截屏2022-11-30 22 53 47" src="https://user-images.githubusercontent.com/67589441/204829453-86f5297b-0fcb-41c4-adbf-914bb9060fef.png">

**Comment by jun-zeng** [comment]
You may refer to [driver.py](https://github.com/jun-zeng/ShadeWatcher/blob/main/recommend/driver.py) to see how to obtain recommendation results.

**Comment by wang1028-yu** [comment]
I' m sorry, can you give a simple example about how to use driver.py to recommend?
