### ISSUE TITLE
whether malicious node appear in trainset ？

### ISSUE THREAD

**Issue by luolo-cry** [jun-zeng/ShadeWatcher#9]
Hello, I think your idea of modeling system interaction as a recommendation task is very cool. 
But I want to know:  ShadeWatcher is a offline model, if malicious node appear in trainset？if not, how to treat the new node(cause malicious node not appear in trainset), if yes, the malicious interaction is removed from KG but remains the malicious node？

**Comment by jun-zeng** [comment]
Hi, we do not include malicious behaviors (both malicious nodes and interactions) in the training set. Every node (both new and old nodes) will be given an embedding (vector) by training TransR. These embeddings are later used by GNN for recommendations.

**Comment by luolo-cry** [comment]
Thanks for your quick reply. I just read the code, i found the train\valid\test are spilted randomly at `inter_train_data, inter_test_val_data = train_test_split(inter_data, test_size=self.test_size + self.val_size, random_state=2021)
        inter_test_data, inter_val_data = train_test_split(inter_test_val_data, test_size=self.val_size/(self.test_size + self.val_size), random_state=2021)` in recommend/util/base_data.py. So i thought the nodes in train are same with nodes in test\valid, malicious nodes and interactions didn't appear in testset? Suppose that a real malicious interaction occured, but the node didn't appear in trainset, how can i detect it ? Thx for your reply

**Comment by jun-zeng** [comment]
In real-world settings, you may encounter previously unseen system entities, which is known as an OOV problem in the NLP domain. One potential solution is to retrain the embedding space using TransR.

**Comment by jun-zeng** [comment]
You can find more information in Appendix A (Discussion of Online Detection) in our paper (https://jun-zeng.github.io/file/shadewatcher_paper.pdf).

**Comment by luolo-cry** [comment]
Thank you for your enthusiastic reply
